USE universidad;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno'ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = 'alumno' AND telefono IS NULL;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%k';
SELECT nombre FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT per.apellido1, per.apellido2, per.nombre, dep.nombre AS nombre_departamento FROM persona per JOIN profesor prof ON per.id = prof.id_profesor JOIN departamento dep ON prof.id_departamento = dep.id WHERE per.tipo = 'profesor' ORDER BY per.apellido1 ASC, per.apellido2 ASC, per.nombre ASC;
SELECT asi.nombre AS nombre_asignatura, ce.anyo_inicio, ce.anyo_fin FROM persona per JOIN alumno_se_matricula_asignatura asm ON per.id = asm.id_alumno JOIN asignatura asi ON asm.id_asignatura = asi.id JOIN curso_escolar ce ON asm.id_curso_escolar = ce.id WHERE per.nif = '26902806M';
SELECT DISTINCT dep.nombre FROM departamento dep JOIN profesor prof ON dep.id = prof.id_departamento JOIN asignatura asi ON prof.id_profesor = asi.id_profesor JOIN grado gra ON asi.id_grado = gra.id WHERE gra.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT per.nombre, per.apellido1, per.apellido2 FROM persona per JOIN alumno_se_matricula_asignatura asm ON per.id = asm.id_alumno JOIN curso_escolar ce ON asm.id_curso_escolar = ce.id WHERE ce.anyo_inicio = 2018 AND ce.anyo_fin = 2019;
SELECT dep.nombre AS nombre_departamento, per.apellido1, per.apellido2, per.nombre FROM profesor prof LEFT JOIN departamento dep ON prof.id_departamento = dep.id JOIN persona per ON prof.id_profesor = per.id ORDER BY dep.nombre ASC, per.apellido1 ASC, per.apellido2 ASC, per.nombre ASC;
SELECT per.nombre, per.apellido1, per.apellido2 FROM profesor prof LEFT JOIN departamento dep ON prof.id_departamento = dep.id JOIN persona per ON prof.id_profesor = per.id ORDER BY dep.nombre ASC, per.apellido1 ASC, per.apellido2 ASC, per.nombre ASC;
SELECT dep.nombre FROM departamento dep LEFT JOIN profesor prof ON dep.id = prof.id_departamento WHERE prof.id_profesor IS NULL;
SELECT per.nombre, per.apellido1, per.apellido2 FROM profesor prof LEFT JOIN asignatura asi ON prof.id_profesor = asi.id_profesor JOIN persona per ON prof.id_profesor = per.id WHERE asi.id_profesor IS NULL;
SELECT asi.nombre FROM asignatura asi LEFT JOIN profesor prof ON asi.id_profesor = prof.id_profesor WHERE asi.id_profesor IS NULL;
SELECT DISTINCT dep.nombre FROM departamento dep LEFT JOIN profesor prof ON dep.id = prof.id_departamento LEFT JOIN asignatura asi ON prof.id_profesor = asi.id_profesor LEFT JOIN alumno_se_matricula_asignatura asm ON asi.id = asm.id_asignatura WHERE asm.id_asignatura IS NULL;
SELECT COUNT(*) AS 'Total alumnos' FROM persona WHERE tipo = 'alumno';
SELECT COUNT(*) AS 'Alumnos nacidos en el 1999' FROM persona WHERE YEAR(fecha_nacimiento) = 1999 AND tipo = 'alumno'; 
SELECT dep.nombre AS 'Nombre Departamento', COUNT(per.id) AS 'Nombre Profesores' FROM departamento dep JOIN profesor prof ON prof.id_departamento = dep.id JOIN persona per ON prof.id_profesor = per.id AND per.tipo = 'profesor' GROUP BY dep.nombre HAVING COUNT(per.id) > 0 ORDER BY COUNT(per.id) DESC;
SELECT dep.nombre AS 'Nombre Departamento', COALESCE(COUNT(per.id), 0) AS 'Nombre Profesores' FROM departamento dep LEFT JOIN profesor prof ON prof.id_departamento = dep.id LEFT JOIN persona per ON prof.id_profesor = per.id AND per.tipo = 'profesor' GROUP BY dep.nombre;
SELECT gra.nombre AS 'Nombre Grado', COALESCE(COUNT(asi.id), 0) AS 'Nombre Asignaturas' FROM grado gra LEFT JOIN asignatura asi ON gra.id = asi.id_grado GROUP BY gra.nombre ORDER BY COUNT(asi.id) DESC;
SELECT gra.nombre AS 'Nombre Grado', COUNT(asi.id) AS 'Nombre Asignaturas' FROM grado gra JOIN asignatura asi ON gra.id = asi.id_grado GROUP BY gra.nombre HAVING COUNT(asi.id) > 40;
SELECT gra.nombre AS 'Nombre Grado', asi.tipo AS 'Tipos Asignatura', SUM(asi.creditos) AS 'Suma Creditos' FROM grado gra JOIN asignatura asi ON gra.id = asi.id_grado GROUP BY gra.nombre, asi.tipo;
SELECT ce.anyo_inicio AS 'Año Inicio', COUNT(DISTINCT asm.id_alumno) AS 'Nombre Alumnos Matriculados' FROM curso_escolar ce LEFT JOIN alumno_se_matricula_asignatura asm ON ce.id = asm.id_curso_escolar GROUP BY ce.anyo_inicio ORDER BY ce.anyo_inicio;
SELECT per.id, per.nombre, per.apellido1, per.apellido2, COALESCE(COUNT(asi.id), 0) AS 'Nombre Asignaturas' FROM persona per LEFT JOIN profesor prof ON prof.id_profesor = per.id AND per.tipo = 'profesor' LEFT JOIN asignatura asi ON prof.id_profesor = asi.id_profesor GROUP BY per.id ORDER BY COUNT(asi.id) DESC;
SELECT * FROM persona WHERE tipo = 'alumno' ORDER BY fecha_nacimiento DESC LIMIT 1;
SELECT per.nombre, per.apellido1, per.apellido2 FROM profesor prof JOIN persona per ON prof.id_profesor = per.id AND per.tipo = 'profesor' LEFT JOIN asignatura asi ON prof.id_profesor = asi.id_profesor WHERE prof.id_departamento IS NOT NULL AND asi.id IS NULL;
